# Generated by Django 5.2 on 2025-05-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('picture', models.ImageField(blank=True, default='img/profile-icon.webp', null=True, upload_to='usersPic/')),
                ('password', models.CharField(max_length=200)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=False)),
                ('LastSignDate', models.DateTimeField(auto_now_add=True)),
                ('is_visble', models.BooleanField(default=True)),
            ],
        ),
    ]
