# Generated by Django 5.2 on 2025-05-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='default/profile-icon.webp', null=True, upload_to='usersPic/'),
        ),
    ]
