# Generated by Django 5.2 on 2025-05-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bloquedA', models.BooleanField(default=False)),
                ('is_bloquedB', models.BooleanField(default=False)),
                ('is_visibleA', models.BooleanField(default=True)),
                ('is_visibleb', models.BooleanField(default=True)),
                ('user_idA', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_as_userA', to='user.user')),
                ('user_idB', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chats_as_userB', to='user.user')),
            ],
        ),
    ]
